"""add training fields

Revision ID: 96bfb519e150
Revises: 
Create Date: 2026-09-19 12:27:06.537265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bfb519e150'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "trainings",
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=False,
            server_default="general_awareness"
        )
    )

    op.add_column(
        "trainings",
        sa.Column(
            "difficulty",
            sa.String(length=50),
            nullable=False,
            server_default="beginner"
        )
    )

    op.add_column(
        "trainings",
        sa.Column(
            "score",
            sa.Integer(),
            nullable=True
        )
    )

    op.alter_column(
        "trainings",
        "simulation_id",
        existing_type=sa.INTEGER(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'simulation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trainings', 'score')
    op.drop_column('trainings', 'difficulty')
    op.drop_column('trainings', 'category')
    # ### end Alembic commands ###
